tools: dcc: echo fix

diff --git a/tools/dcc b/tools/dcc
--- a/tools/dcc
+++ b/tools/dcc
@@ -8,7 +8,7 @@ PROG=""
 while [ -n "$1" ] ; do
 	case "$1" in
 	"-o")
-		if [ -z "$2" ] ; then echo "Usage:\ndcc -o <target> -- <l1 option> ..." 1>&2 ; exit 1 ; fi
+		if [ -z "$2" ] ; then echo -e "Usage:\ndcc -o <target> -- <l1 option> ..." 1>&2 ; exit 1 ; fi
 		PROG="$2"
 		shift
 	;;
@@ -17,7 +17,7 @@ while [ -n "$1" ] ; do
 		break
 	;;
 	*)
-		echo "Unknown option: $1\nUsage:\ndcc -o <target> -- <l1 option> ..." 1>&2
+		echo -e "Unknown option: $1\nUsage:\ndcc -o <target> -- <l1 option> ..." 1>&2
 		exit 1
 	;;
 	esac
@@ -25,14 +25,14 @@ while [ -n "$1" ] ; do
 done
 
 if [ -z "${PROG}" ] ; then
-	echo "Usage:\ndcc -o <target> <l1 option> ..." 1>&2 ; exit 1
+	echo -e "Usage:\ndcc -o <target> -- <l1 option> ..." 1>&2 ; exit 1
 fi
 
 rm -f ${PROG}
 
 T=`mktemp -t heapobj`
 if [ -z "${T}" ] ; then
-	echo "unable to create tempfile" 1>&2
+	echo -e "unable to create tempfile" 1>&2
 	exit 1
 fi
 T="${T}.o"
@@ -42,7 +42,7 @@ if [ -f "${T}" ] ; then
 fi
 
 if [ -z "${PROG}" ] ; then
-	echo "no prog"
+	echo -e "no prog"
 	exit 1
 fi
 
